# coding: utf-8

"""
    TransferMovilAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from enzona_transfermovil.models.full_operations_operation_amount_details import FullOperationsOperationAmountDetails

class TestFullOperationsOperationAmountDetails(unittest.TestCase):
    """FullOperationsOperationAmountDetails unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> FullOperationsOperationAmountDetails:
        """Test FullOperationsOperationAmountDetails
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `FullOperationsOperationAmountDetails`
        """
        model = FullOperationsOperationAmountDetails()
        if include_optional:
            return FullOperationsOperationAmountDetails(
                shipping = 56,
                tax = 56,
                discount = 56,
                tip = 56
            )
        else:
            return FullOperationsOperationAmountDetails(
        )
        """

    def testFullOperationsOperationAmountDetails(self):
        """Test FullOperationsOperationAmountDetails"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
