# coding: utf-8

"""
    TransferMovilAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from enzona_transfermovil.models.payment_summary_info import PaymentSummaryInfo

class TestPaymentSummaryInfo(unittest.TestCase):
    """PaymentSummaryInfo unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PaymentSummaryInfo:
        """Test PaymentSummaryInfo
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PaymentSummaryInfo`
        """
        model = PaymentSummaryInfo()
        if include_optional:
            return PaymentSummaryInfo(
                id = '',
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                update_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                state = 'created',
                operations = enzona_transfermovil.models.payment_summary_info_operations.paymentSummaryInfo_operations(
                    operation = enzona_transfermovil.models.payment_summary_info_operations_operation.paymentSummaryInfo_operations_operation(
                        amount = enzona_transfermovil.models.payment_summary_info_operations_operation_amount.paymentSummaryInfo_operations_operation_amount(
                            total = 56, 
                            currency = 'CUP', 
                            details = enzona_transfermovil.models.payment_summary_info_operations_operation_amount_details.paymentSummaryInfo_operations_operation_amount_details(
                                tip = '', 
                                tax = 56, 
                                shipping = 56, ), ), 
                        bank_debit_details = enzona_transfermovil.models.payment_summary_info_operations_operation_bank_debit_details.paymentSummaryInfo_operations_operation_bank_debit_details(
                            trans_amount = '', 
                            currency = 'CUP', 
                            exchange_rate = 56, 
                            discount = 56, ), 
                        description = '', 
                        merchant_op_id = '', 
                        invoice_id = '', ), )
            )
        else:
            return PaymentSummaryInfo(
        )
        """

    def testPaymentSummaryInfo(self):
        """Test PaymentSummaryInfo"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
