# coding: utf-8

"""
    TransferMovilAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from enzona_transfermovil.models.payment_summary_info_operations_operation_amount import PaymentSummaryInfoOperationsOperationAmount

class TestPaymentSummaryInfoOperationsOperationAmount(unittest.TestCase):
    """PaymentSummaryInfoOperationsOperationAmount unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PaymentSummaryInfoOperationsOperationAmount:
        """Test PaymentSummaryInfoOperationsOperationAmount
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PaymentSummaryInfoOperationsOperationAmount`
        """
        model = PaymentSummaryInfoOperationsOperationAmount()
        if include_optional:
            return PaymentSummaryInfoOperationsOperationAmount(
                total = 56,
                currency = 'CUP',
                details = enzona_transfermovil.models.payment_summary_info_operations_operation_amount_details.paymentSummaryInfo_operations_operation_amount_details(
                    tip = '', 
                    tax = 56, 
                    shipping = 56, )
            )
        else:
            return PaymentSummaryInfoOperationsOperationAmount(
        )
        """

    def testPaymentSummaryInfoOperationsOperationAmount(self):
        """Test PaymentSummaryInfoOperationsOperationAmount"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
