# coding: utf-8

"""
    TransferMovilAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from enzona_transfermovil.models.payment_summary_info_operations import PaymentSummaryInfoOperations

class TestPaymentSummaryInfoOperations(unittest.TestCase):
    """PaymentSummaryInfoOperations unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PaymentSummaryInfoOperations:
        """Test PaymentSummaryInfoOperations
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PaymentSummaryInfoOperations`
        """
        model = PaymentSummaryInfoOperations()
        if include_optional:
            return PaymentSummaryInfoOperations(
                operation = enzona_transfermovil.models.payment_summary_info_operations_operation.paymentSummaryInfo_operations_operation(
                    amount = enzona_transfermovil.models.payment_summary_info_operations_operation_amount.paymentSummaryInfo_operations_operation_amount(
                        total = 56, 
                        currency = 'CUP', 
                        details = enzona_transfermovil.models.payment_summary_info_operations_operation_amount_details.paymentSummaryInfo_operations_operation_amount_details(
                            tip = '', 
                            tax = 56, 
                            shipping = 56, ), ), 
                    bank_debit_details = enzona_transfermovil.models.payment_summary_info_operations_operation_bank_debit_details.paymentSummaryInfo_operations_operation_bank_debit_details(
                        trans_amount = '', 
                        currency = 'CUP', 
                        exchange_rate = 56, 
                        discount = 56, ), 
                    description = '', 
                    merchant_op_id = '', 
                    invoice_id = '', )
            )
        else:
            return PaymentSummaryInfoOperations(
        )
        """

    def testPaymentSummaryInfoOperations(self):
        """Test PaymentSummaryInfoOperations"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
