# coding: utf-8

"""
    TransferMovilAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from enzona_transfermovil.models.payment_full_info_payer import PaymentFullInfoPayer

class TestPaymentFullInfoPayer(unittest.TestCase):
    """PaymentFullInfoPayer unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PaymentFullInfoPayer:
        """Test PaymentFullInfoPayer
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PaymentFullInfoPayer`
        """
        model = PaymentFullInfoPayer()
        if include_optional:
            return PaymentFullInfoPayer(
                payer_info = enzona_transfermovil.models.payment_full_info_payer_payer_info.paymentFullInfo_payer_payer_info(
                    username = '', 
                    first_name = '', 
                    last_name = '', 
                    payer_id = '', )
            )
        else:
            return PaymentFullInfoPayer(
        )
        """

    def testPaymentFullInfoPayer(self):
        """Test PaymentFullInfoPayer"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
