# coding: utf-8

"""
    TransferMovilAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from enzona_transfermovil.api.permite_obtener_una_devolucion_api import PermiteObtenerUnaDevolucionApi


class TestPermiteObtenerUnaDevolucionApi(unittest.TestCase):
    """PermiteObtenerUnaDevolucionApi unit test stubs"""

    def setUp(self) -> None:
        self.api = PermiteObtenerUnaDevolucionApi()

    def tearDown(self) -> None:
        pass

    def test_refunds_refund_id_get(self) -> None:
        """Test case for refunds_refund_id_get

        """
        pass


if __name__ == '__main__':
    unittest.main()
