# coding: utf-8

"""
    TransferMovilAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from enzona_transfermovil.api.permite_obtener_un_pago_api import PermiteObtenerUnPagoApi


class TestPermiteObtenerUnPagoApi(unittest.TestCase):
    """PermiteObtenerUnPagoApi unit test stubs"""

    def setUp(self) -> None:
        self.api = PermiteObtenerUnPagoApi()

    def tearDown(self) -> None:
        pass

    def test_payments_merchant_op_id_get(self) -> None:
        """Test case for payments_merchant_op_id_get

        """
        pass


if __name__ == '__main__':
    unittest.main()
