# coding: utf-8

"""
    TransferMovilAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from enzona_transfermovil.models.pagination_links import PaginationLinks

class TestPaginationLinks(unittest.TestCase):
    """PaginationLinks unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PaginationLinks:
        """Test PaginationLinks
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PaginationLinks`
        """
        model = PaginationLinks()
        if include_optional:
            return PaginationLinks(
                first_page = enzona_transfermovil.models.pagination_links_first_page.pagination_links_first_page(
                    href = '', ),
                last_page = enzona_transfermovil.models.pagination_links_first_page.pagination_links_first_page(
                    href = '', ),
                next_page = enzona_transfermovil.models.pagination_links_first_page.pagination_links_first_page(
                    href = '', ),
                prev_page = enzona_transfermovil.models.pagination_links_first_page.pagination_links_first_page(
                    href = '', )
            )
        else:
            return PaginationLinks(
        )
        """

    def testPaginationLinks(self):
        """Test PaginationLinks"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
