# coding: utf-8

"""
    TransferMovilAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from enzona_transfermovil.api.permite_crear_una_devolucion_api import PermiteCrearUnaDevolucionApi


class TestPermiteCrearUnaDevolucionApi(unittest.TestCase):
    """PermiteCrearUnaDevolucionApi unit test stubs"""

    def setUp(self) -> None:
        self.api = PermiteCrearUnaDevolucionApi()

    def tearDown(self) -> None:
        pass

    def test_payments_transaction_uuid_refunds_post(self) -> None:
        """Test case for payments_transaction_uuid_refunds_post

        """
        pass


if __name__ == '__main__':
    unittest.main()
