# coding: utf-8

"""
    TransferMovilAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from enzona_transfermovil.models.payment_refund_operations_amount import PaymentRefundOperationsAmount

class TestPaymentRefundOperationsAmount(unittest.TestCase):
    """PaymentRefundOperationsAmount unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PaymentRefundOperationsAmount:
        """Test PaymentRefundOperationsAmount
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PaymentRefundOperationsAmount`
        """
        model = PaymentRefundOperationsAmount()
        if include_optional:
            return PaymentRefundOperationsAmount(
                total = 56,
                details = enzona_transfermovil.models.payment_refund_operations_amount_details.paymentRefundOperations_amount_details(
                    shipping = 56, 
                    tax = 56, 
                    discount = 1.337, 
                    tip = 1.337, 
                    refunded = 56, 
                    total_refunded = 56, )
            )
        else:
            return PaymentRefundOperationsAmount(
        )
        """

    def testPaymentRefundOperationsAmount(self):
        """Test PaymentRefundOperationsAmount"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
