# coding: utf-8

"""
    TransferMovilAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from enzona_transfermovil.models.payment_full_info_payer_payer_info import PaymentFullInfoPayerPayerInfo

class TestPaymentFullInfoPayerPayerInfo(unittest.TestCase):
    """PaymentFullInfoPayerPayerInfo unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PaymentFullInfoPayerPayerInfo:
        """Test PaymentFullInfoPayerPayerInfo
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PaymentFullInfoPayerPayerInfo`
        """
        model = PaymentFullInfoPayerPayerInfo()
        if include_optional:
            return PaymentFullInfoPayerPayerInfo(
                username = '',
                first_name = '',
                last_name = '',
                payer_id = ''
            )
        else:
            return PaymentFullInfoPayerPayerInfo(
        )
        """

    def testPaymentFullInfoPayerPayerInfo(self):
        """Test PaymentFullInfoPayerPayerInfo"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
