# coding: utf-8

"""
    TransferMovilAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from enzona_transfermovil.models.full_operations_operation_items_inner import FullOperationsOperationItemsInner

class TestFullOperationsOperationItemsInner(unittest.TestCase):
    """FullOperationsOperationItemsInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> FullOperationsOperationItemsInner:
        """Test FullOperationsOperationItemsInner
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `FullOperationsOperationItemsInner`
        """
        model = FullOperationsOperationItemsInner()
        if include_optional:
            return FullOperationsOperationItemsInner(
                description = '',
                quantity = 56,
                price = 56,
                tax = 56,
                name = ''
            )
        else:
            return FullOperationsOperationItemsInner(
        )
        """

    def testFullOperationsOperationItemsInner(self):
        """Test FullOperationsOperationItemsInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
