# coding: utf-8

"""
    TransferMovilAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from enzona_transfermovil.models.links_schema import LinksSchema

class TestLinksSchema(unittest.TestCase):
    """LinksSchema unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> LinksSchema:
        """Test LinksSchema
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `LinksSchema`
        """
        model = LinksSchema()
        if include_optional:
            return LinksSchema(
                rel = 'confirm',
                method = 'REDIRECT',
                href = 'https://enzona.xetid.cu/checkout/1940841ec89d4f32aef06c813825920b/login'
            )
        else:
            return LinksSchema(
        )
        """

    def testLinksSchema(self):
        """Test LinksSchema"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
