# coding: utf-8

"""
    TransferMovilAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from enzona_transfermovil.models.full_operations_operation import FullOperationsOperation

class TestFullOperationsOperation(unittest.TestCase):
    """FullOperationsOperation unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> FullOperationsOperation:
        """Test FullOperationsOperation
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `FullOperationsOperation`
        """
        model = FullOperationsOperation()
        if include_optional:
            return FullOperationsOperation(
                description = '',
                invoice_number = '',
                merchant_op_id = '',
                terminal_id = '',
                amount = enzona_transfermovil.models.full_operations_operation_amount.fullOperations_operation_amount(
                    total = 56, 
                    details = enzona_transfermovil.models.full_operations_operation_amount_details.fullOperations_operation_amount_details(
                        shipping = 56, 
                        tax = 56, 
                        discount = 56, 
                        tip = 56, ), ),
                items = [
                    enzona_transfermovil.models.full_operations_operation_items_inner.fullOperations_operation_items_inner(
                        description = '', 
                        quantity = 56, 
                        price = 56, 
                        tax = 56, 
                        name = '', )
                    ]
            )
        else:
            return FullOperationsOperation(
        )
        """

    def testFullOperationsOperation(self):
        """Test FullOperationsOperation"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
