# coding: utf-8

"""
    TransferMovilAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from enzona_transfermovil.models.payments_post_request_items_inner import PaymentsPostRequestItemsInner

class TestPaymentsPostRequestItemsInner(unittest.TestCase):
    """PaymentsPostRequestItemsInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PaymentsPostRequestItemsInner:
        """Test PaymentsPostRequestItemsInner
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PaymentsPostRequestItemsInner`
        """
        model = PaymentsPostRequestItemsInner()
        if include_optional:
            return PaymentsPostRequestItemsInner(
                name = '',
                description = '',
                quantity = 56,
                price = 1.337,
                tax = 1.337
            )
        else:
            return PaymentsPostRequestItemsInner(
        )
        """

    def testPaymentsPostRequestItemsInner(self):
        """Test PaymentsPostRequestItemsInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
