# coding: utf-8

"""
    TransferMovilAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from enzona_transfermovil.models.payment_summary_info_operations_operation_amount_details import PaymentSummaryInfoOperationsOperationAmountDetails

class TestPaymentSummaryInfoOperationsOperationAmountDetails(unittest.TestCase):
    """PaymentSummaryInfoOperationsOperationAmountDetails unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PaymentSummaryInfoOperationsOperationAmountDetails:
        """Test PaymentSummaryInfoOperationsOperationAmountDetails
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PaymentSummaryInfoOperationsOperationAmountDetails`
        """
        model = PaymentSummaryInfoOperationsOperationAmountDetails()
        if include_optional:
            return PaymentSummaryInfoOperationsOperationAmountDetails(
                tip = '',
                tax = 56,
                shipping = 56
            )
        else:
            return PaymentSummaryInfoOperationsOperationAmountDetails(
        )
        """

    def testPaymentSummaryInfoOperationsOperationAmountDetails(self):
        """Test PaymentSummaryInfoOperationsOperationAmountDetails"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
