# coding: utf-8

"""
    TransferMovilAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from enzona_transfermovil.api.permite_crear_un_pago_api import PermiteCrearUnPagoApi


class TestPermiteCrearUnPagoApi(unittest.TestCase):
    """PermiteCrearUnPagoApi unit test stubs"""

    def setUp(self) -> None:
        self.api = PermiteCrearUnPagoApi()

    def tearDown(self) -> None:
        pass

    def test_payments_post(self) -> None:
        """Test case for payments_post

        """
        pass


if __name__ == '__main__':
    unittest.main()
