# coding: utf-8

"""
    TransferMovilAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from enzona_transfermovil.models.payments_post_request import PaymentsPostRequest

class TestPaymentsPostRequest(unittest.TestCase):
    """PaymentsPostRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PaymentsPostRequest:
        """Test PaymentsPostRequest
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PaymentsPostRequest`
        """
        model = PaymentsPostRequest()
        if include_optional:
            return PaymentsPostRequest(
                description = '',
                currency = 'CUP',
                amount = 1.337,
                items = [
                    enzona_transfermovil.models._payments_post_request_items_inner._payments_post_request_items_inner(
                        name = '', 
                        description = '', 
                        quantity = 56, 
                        price = 1.337, 
                        tax = 1.337, )
                    ],
                merchant_op_id = '123456789123',
                invoice_number = '1212',
                return_url = 'https://mymerchant.cu/return',
                cancel_url = 'https://mymerchant.cu/cancel',
                terminal_id = '12356',
                merchant_uuid = 'f89c79c8dfbd43939cdc43cf47b1ee47',
                valid_time = 1.337,
                username = 'user'
            )
        else:
            return PaymentsPostRequest(
        )
        """

    def testPaymentsPostRequest(self):
        """Test PaymentsPostRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
