# coding: utf-8

"""
    TransferMovilAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from enzona_transfermovil.models.payment_full_info import PaymentFullInfo

class TestPaymentFullInfo(unittest.TestCase):
    """PaymentFullInfo unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PaymentFullInfo:
        """Test PaymentFullInfo
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PaymentFullInfo`
        """
        model = PaymentFullInfo()
        if include_optional:
            return PaymentFullInfo(
                id = '',
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                update_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                state = 'created',
                payer = enzona_transfermovil.models.payment_full_info_payer.paymentFullInfo_payer(
                    payer_info = enzona_transfermovil.models.payment_full_info_payer_payer_info.paymentFullInfo_payer_payer_info(
                        username = '', 
                        first_name = '', 
                        last_name = '', 
                        payer_id = '', ), )
            )
        else:
            return PaymentFullInfo(
        )
        """

    def testPaymentFullInfo(self):
        """Test PaymentFullInfo"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
